"""
DATA CONTRACT (see docs/data_contracts.md):
    Input:  clusters (list[dict]), scored_clusters (list[dict]), goal (str)
    Output: OST dict {goal, opportunities: [...]} with all score fields injected

Models:
    Primary:  llama-3.3-70b-versatile
    Fallback: llama-3.1-8b-instant

Score fields injected post-parse from scored_clusters (never LLM-generated):
    importance, satisfaction, source_type_diversity,
    odi_score, evidence_robustness, priority_score
"""

import json
import os
import re
from pathlib import Path
from groq import Groq, APIStatusError

# ── Constants ─────────────────────────────────────────────────────────────────

_PRIMARY_MODEL = "llama-3.3-70b-versatile"
_FALLBACK_MODEL = "llama-3.1-8b-instant"
_MAX_TOKENS = 4096
_SYSTEM_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "system_prompt.txt"

# Score fields to inject from scored_clusters — never generated by the LLM.
# Also used by _validate_ost to confirm the LLM did NOT generate them.
_INJECT_FIELDS = [
    "importance",
    "satisfaction",
    "source_type_diversity",
    "odi_score",
    "evidence_robustness",
    "priority_score",
]

# Fields the LLM must never produce. Superset of _INJECT_FIELDS — includes the
# retired "opportunity_score" field in case an older prompt version slips through.
_FORBIDDEN_FIELDS = set(_INJECT_FIELDS) | {"opportunity_score"}

# Valid risk labels as defined in the system prompt rubric.
_VALID_RISK_VALUES = {"low", "medium", "high"}

# Valid confidence labels for jtbd_confidence.
_VALID_CONFIDENCE_VALUES = {"high", "medium", "low"}

# Clusters with this many chunks or fewer get a deterministic low-confidence
# override post-parse, regardless of what the LLM returned. With so little
# evidence the model is likely abstracting beyond the quotes.
MIN_CLUSTER_SIZE = 3


# ── Custom exception ───────────────────────────────────────────────────────────


class _OSTValidationError(ValueError):
    """
    Raised by _validate_ost when a syntactically valid OST dict fails
    structural or content checks. Distinct from json.JSONDecodeError so
    build_ost can log the failure reason accurately before falling back.
    """

    pass


# ── Internal helpers ───────────────────────────────────────────────────────────


def _load_system_prompt() -> str:
    """Load system prompt from file. Raises clearly if missing."""
    if not _SYSTEM_PROMPT_PATH.exists():
        raise FileNotFoundError(
            f"System prompt not found at {_SYSTEM_PROMPT_PATH}. "
            "Make sure prompts/system_prompt.txt is committed to the repo."
        )
    return _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()


def _build_user_message(clusters: list[dict], goal: str, context_block: str = "") -> str:
    """
    T-10 hybrid chunk selection: each cluster contributes 3 chunks total —
    the top 2 by HDBSCAN membership probability (cluster core, theme signal)
    plus 1 boundary chunk (lowest membership, texture/outlier language).

    cluster_size is passed so the model can calibrate jtbd_confidence per Rule 9.
    context_block is appended after cluster evidence if non-empty, omitted if empty.
    """

    def _format_chunk(chunk: dict) -> dict:
        return {"text": chunk["text"], "source_type": chunk["source_type"]}

    slim_clusters: list[dict] = []
    for c in clusters:
        core_chunks = [_format_chunk(ch) for ch in c["representative_chunks"][:2]]

        boundary_list = c.get("boundary_chunks") or []
        if boundary_list:
            boundary_chunk = _format_chunk(boundary_list[0])
        elif len(c["representative_chunks"]) > 2:
            boundary_chunk = _format_chunk(c["representative_chunks"][2])
        else:
            boundary_chunk = None

        chunks_for_prompt = core_chunks + ([boundary_chunk] if boundary_chunk else [])

        slim_clusters.append(
            {
                "cluster_id": c["cluster_id"],
                "cluster_size": len(c.get("all_chunk_ids", [])),
                "representative_chunks": chunks_for_prompt,
            }
        )

    msg = f"Goal: {goal}\n\nClusters:\n{json.dumps(slim_clusters, indent=2)}"
    if context_block:
        msg += f"\n\nStakeholder context:\n{context_block}"
    return msg


def _call_groq(client: Groq, model: str, system: str, user: str) -> str:
    """Call Groq and return the raw text response."""
    response = client.chat.completions.create(
        model=model,
        max_tokens=_MAX_TOKENS,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    )
    return response.choices[0].message.content.strip()


def _parse_json(raw: str) -> dict:
    """
    Attempt to parse JSON from an LLM response using a cascade of repair
    strategies. Each strategy tries to recover from a different class of
    LLM formatting mistake.

    Repair cascade (stops at the first success):
        0. Fence stripping     — model wrapped JSON in ```...``` blocks
        1. Clean parse         — response was already valid JSON after fence strip
        2. raw_decode          — model added preamble text before the opening brace,
                                 or appended explanation text after the closing brace
        3. Trailing commas     — model emitted trailing commas before ] or }
        4. raw_decode + commas — model did both: preamble/suffix AND trailing commas

    Raises json.JSONDecodeError only when all four strategies fail, so that
    the caller (build_ost) can escalate to the fallback model.
    """

    # ── Repair 0: strip markdown fences ──────────────────────────────────────
    # Some models wrap their JSON in ```json ... ``` even when told not to.
    # We strip the fence lines so subsequent parse attempts work on clean text.
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        # Drop the opening fence line; also drop the closing ``` line if present.
        cleaned = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    # ── Repair 1: clean parse ─────────────────────────────────────────────────
    # Best case: the response was valid JSON after fence stripping. Try first
    # before attempting any heavier repairs.
    try:
        result = json.loads(cleaned)
        print("[llm] JSON parsed cleanly (no repairs needed)")
        return result
    except json.JSONDecodeError:
        # Not valid JSON as-is — continue to repair strategies below.
        pass

    # ── Repair 2: raw_decode from first '{' ───────────────────────────────────
    # json.JSONDecoder.raw_decode(s, idx) starts decoding at position idx and
    # stops as soon as it has read one complete JSON value, ignoring everything
    # after it. This handles two failure modes in a single step:
    #   (a) Preamble text — model says "Here is your JSON:" before the brace.
    #   (b) Trailing text — model appends "Let me know if..." after the brace.
    # By starting at the first '{' we skip the preamble; raw_decode ignores
    # anything beyond the closing '}' automatically.
    brace_pos = cleaned.find("{")
    if brace_pos != -1:
        try:
            obj, _ = json.JSONDecoder().raw_decode(cleaned, brace_pos)
            print(
                f"[llm] JSON repair succeeded via: raw_decode "
                f"(skipped {brace_pos} chars of preamble)"
            )
            return obj
        except json.JSONDecodeError:
            # The JSON block itself is malformed — try more repairs below.
            pass

    # ── Repair 3: trailing comma removal ─────────────────────────────────────
    # LLMs occasionally emit trailing commas before ] or } — valid in many
    # languages but illegal in JSON. A simple regex catches the common cases:
    #   {"key": "value",}   →  {"key": "value"}
    #   ["a", "b",]         →  ["a", "b"]
    # We apply the regex to the full cleaned string, then retry json.loads.
    comma_cleaned = re.sub(r",\s*([}\]])", r"\1", cleaned)
    try:
        result = json.loads(comma_cleaned)
        print("[llm] JSON repair succeeded via: trailing comma removal")
        return result
    except json.JSONDecodeError:
        # Still not valid — try combining both repairs.
        pass

    # ── Repair 4: raw_decode + trailing comma removal ─────────────────────────
    # Last-ditch: the model added preamble/trailing text AND trailing commas.
    # Slice from the first '{', strip trailing commas, then use raw_decode.
    # raw_decode is used again (rather than json.loads) to also tolerate any
    # remaining trailing text after the repaired closing brace.
    if brace_pos != -1:
        try:
            slice_from_brace = cleaned[brace_pos:]
            # Strip trailing commas in the sliced block first.
            slice_comma_cleaned = re.sub(r",\s*([}\]])", r"\1", slice_from_brace)
            obj, _ = json.JSONDecoder().raw_decode(slice_comma_cleaned, 0)
            print(
                "[llm] JSON repair succeeded via: raw_decode + trailing comma removal"
            )
            return obj
        except json.JSONDecodeError:
            pass

    # ── All repairs failed ────────────────────────────────────────────────────
    # Raise so build_ost can escalate to the fallback model. We surface the
    # original raw text in the message to make debugging easier.
    print("[llm] All JSON repair strategies failed — escalating to fallback model")
    raise json.JSONDecodeError(
        f"All repair strategies exhausted. Raw response (first 300 chars): "
        f"{raw[:300]!r}",
        raw,
        0,
    )


def _validate_ost(ost: dict, clusters: list[dict]) -> None:
    """
    Structural and content validation of a parsed OST dict against the input
    clusters. Raises _OSTValidationError with a descriptive message on the
    first problem found.

    This is the guard between _parse_json and _merge_scores. JSON syntax
    correctness (handled by _parse_json) is necessary but not sufficient —
    the LLM can silently drop clusters, invent cluster IDs, or generate
    forbidden score fields while producing perfectly valid JSON.

    Checks performed (in order):
        1.  Opportunity count matches cluster count
        2.  No hallucinated cluster_ids (every opp ID must exist in input)
        3.  No duplicate cluster_ids across opportunities
        4.  No missing clusters (every input cluster has an opportunity)
        5.  All risk values are in {low, medium, high}
        5b. Each opportunity has exactly 2–3 solutions
        6.  No forbidden score fields present on any opportunity
        7.  jtbd_confidence present and in {high, medium, low}
        8.  jtbd_confidence_reason present and non-empty
    """

    # Build the set of cluster_ids we expect to see in the output.
    # This is the ground truth — anything outside this set is hallucinated.
    expected_ids: set[int] = {c["cluster_id"] for c in clusters}
    opportunities: list[dict] = ost.get("opportunities", [])

    # ── Check 1: opportunity count ────────────────────────────────────────────
    # The system prompt instructs the model to return exactly one opportunity
    # per cluster, but LLMs can merge or drop clusters silently.
    if len(opportunities) != len(clusters):
        raise _OSTValidationError(
            f"Opportunity count mismatch: expected {len(clusters)} "
            f"(one per cluster), got {len(opportunities)}."
        )

    # Extract the cluster_id from each opportunity for the remaining checks.
    opp_ids: list[int] = [o.get("cluster_id") for o in opportunities]

    # ── Check 2: no hallucinated cluster_ids ─────────────────────────────────
    # A hallucinated ID means the model invented a cluster that was never in the
    # input. The score merge would silently assign null to all its score fields.
    hallucinated: list[int] = [cid for cid in opp_ids if cid not in expected_ids]
    if hallucinated:
        raise _OSTValidationError(
            f"Hallucinated cluster_ids not present in input clusters: {hallucinated}. "
            f"Valid IDs are: {sorted(expected_ids)}."
        )

    # ── Check 3: no duplicate cluster_ids ────────────────────────────────────
    # Duplicates mean two opportunities reference the same cluster. The score
    # merge would inject the same scores into both, and the PM would see the
    # same cluster twice in the OST tree.
    seen: set[int] = set()
    duplicates: list[int] = []
    for cid in opp_ids:
        if cid in seen:
            duplicates.append(cid)
        seen.add(cid)
    if duplicates:
        raise _OSTValidationError(
            f"Duplicate cluster_ids in opportunities: {duplicates}. "
            f"Each cluster must appear exactly once."
        )

    # ── Check 4: no missing clusters ─────────────────────────────────────────
    # Every input cluster must have a corresponding opportunity. If a cluster
    # is missing, the PM has no JTBD or solutions for that discovery theme.
    # We report the missing IDs explicitly so the error is actionable.
    opp_id_set: set[int] = set(opp_ids)
    missing: list[int] = sorted(expected_ids - opp_id_set)
    if missing:
        raise _OSTValidationError(
            f"No opportunity generated for cluster_ids: {missing}. "
            f"The model dropped {len(missing)} cluster(s) from the output."
        )

    # ── Check 5: risk values ──────────────────────────────────────────────────
    # Collect all risk values from every assumption in every solution and verify
    # they match the rubric. An invalid value (e.g. "very high", None, "") means
    # the model ignored or misread the system prompt.
    invalid_risks: list[str] = []
    for opp in opportunities:
        for solution in opp.get("solutions", []):
            for assumption in solution.get("assumptions", []):
                risk = assumption.get("risk")
                if risk not in _VALID_RISK_VALUES:
                    invalid_risks.append(repr(risk))
    if invalid_risks:
        raise _OSTValidationError(
            f"Invalid risk value(s): {invalid_risks}. "
            f"Must be exactly one of: {sorted(_VALID_RISK_VALUES)}."
        )

    # ── Check 5b: solution count per opportunity ──────────────────────────────
    # The system prompt Rule 2 is CRITICAL: every opportunity must have 2–3
    # solutions. Zero or one solutions is not useful to the PM; more than three
    # means the model ignored the cap. Both cases indicate prompt non-compliance.
    for opp in opportunities:
        n_solutions = len(opp.get("solutions", []))
        if not (2 <= n_solutions <= 3):
            raise _OSTValidationError(
                f"Opportunity cluster_id {opp.get('cluster_id')} has {n_solutions} "
                f"solution(s) — must be exactly 2 or 3 (system prompt Rule 2)."
            )

    # ── Check 6: no forbidden score fields ───────────────────────────────────
    # Score fields are computed deterministically by odi_scorer.py and injected
    # post-parse. If the LLM generated them, we would overwrite them anyway —
    # but allowing it through silently makes the pipeline unauditable and could
    # mask prompt regressions (e.g. an old prompt version that still asks for scores).
    for opp in opportunities:
        found: set[str] = _FORBIDDEN_FIELDS & set(opp.keys())
        if found:
            raise _OSTValidationError(
                f"LLM generated forbidden score field(s) on cluster_id "
                f"{opp.get('cluster_id')}: {sorted(found)}. "
                f"These must be computed by odi_scorer.py, not the LLM."
            )

    # ── Check 7: jtbd_confidence value ───────────────────────────────────────
    # The LLM must generate jtbd_confidence for every opportunity. Invalid or
    # missing values mean the model ignored Rule 9 in the system prompt.
    for opp in opportunities:
        confidence = opp.get("jtbd_confidence")
        if confidence not in _VALID_CONFIDENCE_VALUES:
            raise _OSTValidationError(
                f"Invalid or missing jtbd_confidence on cluster_id "
                f"{opp.get('cluster_id')}: {confidence!r}. "
                f"Must be one of: {sorted(_VALID_CONFIDENCE_VALUES)}."
            )

    # ── Check 8: jtbd_confidence_reason present and non-empty ────────────────
    # The reason must be a non-empty string. An empty string means the model
    # generated the field but provided no explanation — not useful to the PM.
    for opp in opportunities:
        reason = opp.get("jtbd_confidence_reason")
        if not isinstance(reason, str) or not reason.strip():
            raise _OSTValidationError(
                f"Missing or empty jtbd_confidence_reason on cluster_id "
                f"{opp.get('cluster_id')}. Must be a non-empty sentence."
            )

    # All checks passed — return normally (None).
    print(
        f"[llm] OST validation passed: {len(opportunities)} opportunities, "
        f"cluster_ids {sorted(opp_id_set)}"
    )


def _merge_scores(ost: dict, scored_clusters: list[dict]) -> dict:
    """
    Inject score fields from scored_clusters into each opportunity.
    Matches on cluster_id. Sets all score fields to null if no match found.
    Mutates ost in place and returns it.
    """
    scores_by_id: dict[int, dict] = {sc["cluster_id"]: sc for sc in scored_clusters}

    for opportunity in ost.get("opportunities", []):
        cluster_id = opportunity.get("cluster_id")
        sc = scores_by_id.get(cluster_id)

        for field in _INJECT_FIELDS:
            opportunity[field] = sc[field] if sc and field in sc else None

    return ost


def _apply_confidence_override(ost: dict, clusters: list[dict]) -> dict:
    """
    Deterministic post-parse override for jtbd_confidence on sparse clusters.

    Clusters with all_chunk_ids length <= MIN_CLUSTER_SIZE receive:
        jtbd_confidence        = "low"
        jtbd_confidence_reason = a sentence stating the exact chunk count

    This runs after _validate_ost (so the LLM fields are already confirmed
    valid) and before _merge_scores. The override is intentionally explicit —
    the PM sees the chunk count rather than a vague LLM-generated reason,
    which makes it actionable: go collect more evidence for this theme.

    Mutates ost in place and returns it.
    """
    # Build a lookup from cluster_id → chunk count using all_chunk_ids.
    # Note: all_chunk_ids is NOT sent to the LLM (stripped in _build_user_message)
    # so the LLM cannot know the cluster size — the override is the only
    # reliable way to enforce the low-confidence floor for sparse clusters.
    chunk_count_by_id: dict[int, int] = {
        c["cluster_id"]: len(c.get("all_chunk_ids", [])) for c in clusters
    }

    for opportunity in ost.get("opportunities", []):
        cluster_id = opportunity.get("cluster_id")
        chunk_count = chunk_count_by_id.get(cluster_id, 0)

        if chunk_count <= MIN_CLUSTER_SIZE:
            # Override whatever the LLM said — the evidence floor is not met.
            opportunity["jtbd_confidence"] = "low"
            opportunity["jtbd_confidence_reason"] = (
                f"Only {chunk_count} chunk(s) of evidence in this cluster — "
                f"too few to reliably ground all three parts of the JTBD."
            )
            print(
                f"[llm] Confidence override applied to cluster_id {cluster_id}: "
                f"{chunk_count} chunk(s) <= MIN_CLUSTER_SIZE ({MIN_CLUSTER_SIZE})"
            )

    return ost


# ── Public interface ───────────────────────────────────────────────────────────


def build_ost(
    clusters: list[dict],
    scored_clusters: list[dict],
    goal: str,
    context_block: str = "",
) -> dict:
    """
    Call Groq to generate JTBD + solutions for each cluster, then validate
    and inject ODI scores from scored_clusters to produce the final OST dict.

    The pipeline for each model attempt is:
        1. _call_groq  — get raw text from the model
        2. _parse_json — repair and parse JSON syntax
        3. _validate_ost — check structural integrity against input clusters
        4. _merge_scores — inject scores (only reached if validation passes)

    Fallback is triggered when either step 1, 2, or 3 fails for the primary
    model. APIStatusError always bypasses repair/validation and goes straight
    to fallback since there is no response body to recover.

    Args:
        clusters:        output of clusterer.py
        scored_clusters: output of odi_scorer.py — must be populated before calling
        goal:            product goal string from st.session_state["goal"]
        context_block:   optional stakeholder/constraint context from
                         st.session_state["context_block"]. Max 500 words —
                         truncated upstream in upload.py before storage.
                         Injected after cluster evidence in the user message.
                         Omitted entirely if empty — no change to prompt shape.

    Returns:
        OST dict matching the approved schema in docs/llm_output_schema.json

    Raises:
        RuntimeError: if both primary and fallback models fail at any step,
                      with a descriptive message including which clusters are missing
    """
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    system = _load_system_prompt()
    user = _build_user_message(clusters, goal, context_block)

    # We track the primary failure reason as a string so the final RuntimeError
    # (if both models fail) can explain exactly what went wrong at each stage.
    primary_failure_reason: str | None = None
    ost: dict | None = None
    used_fallback: bool = False

    # ── Primary model attempt ─────────────────────────────────────────────────

    # Step 1: API call
    raw: str | None = None
    try:
        raw = _call_groq(client, _PRIMARY_MODEL, system, user)
    except APIStatusError as e:
        # API-level failure (e.g. 429 rate limit, 413 token limit).
        # No response body exists — skip parse and validation entirely.
        primary_failure_reason = f"API error {e.status_code}: {e.message}"
        print(f"[llm] Primary model API error ({e.status_code}), switching to fallback")

    # Steps 2 + 3: parse then validate (only if we have a response)
    if raw is not None:
        try:
            ost = _parse_json(raw)
            # Validation is a separate step from parsing — a syntactically valid
            # JSON can still be structurally wrong (wrong cluster count, hallucinated
            # IDs, forbidden fields). Both failures trigger the same fallback.
            _validate_ost(ost, clusters)
        except json.JSONDecodeError as e:
            primary_failure_reason = f"JSON parse failed after all repairs: {e}"
            print(f"[llm] Primary model JSON unrecoverable, switching to fallback")
            ost = None
        except _OSTValidationError as e:
            primary_failure_reason = f"OST validation failed: {e}"
            print(f"[llm] Primary model OST invalid ({e}), switching to fallback")
            ost = None

    # ── Fallback model attempt ────────────────────────────────────────────────
    # Reached when: primary API call failed, primary JSON was unrecoverable, or
    # primary OST failed structural validation.
    if ost is None:

        # Step 1: fallback API call
        try:
            raw_fallback = _call_groq(client, _FALLBACK_MODEL, system, user)
        except APIStatusError as e:
            raise RuntimeError(
                f"Fallback model API error ({e.status_code}). "
                f"Primary failure was: {primary_failure_reason}. "
                "Check GROQ_API_KEY and request size."
            ) from e

        # Step 2: parse fallback response
        # Parse and validation are kept separate here so the RuntimeError can
        # distinguish between "the fallback also produced broken JSON" vs
        # "the fallback parsed but was structurally wrong".
        try:
            ost_fallback = _parse_json(raw_fallback)
        except json.JSONDecodeError as e:
            raise RuntimeError(
                f"Both models returned invalid JSON after all repair strategies.\n"
                f"  Primary failure:   {primary_failure_reason}\n"
                f"  Fallback JSON error: {e}\n"
                f"  Fallback raw response (first 300 chars): {raw_fallback[:300]!r}"
            ) from e

        # Step 3: validate fallback OST
        # On failure, build a PM-readable message that names the missing clusters
        # so the team knows exactly which discovery themes have no JTBD.
        try:
            _validate_ost(ost_fallback, clusters)
        except _OSTValidationError as e:
            expected_ids = sorted(c["cluster_id"] for c in clusters)
            opp_ids = sorted(
                o.get("cluster_id") for o in ost_fallback.get("opportunities", [])
            )
            missing_ids = sorted(set(expected_ids) - set(opp_ids))
            raise RuntimeError(
                f"Both models produced structurally invalid OST output.\n"
                f"  Primary failure:    {primary_failure_reason}\n"
                f"  Fallback validation error: {e}\n"
                f"  Expected cluster IDs: {expected_ids}\n"
                f"  Returned cluster IDs: {opp_ids}\n"
                f"  Missing cluster IDs:  {missing_ids}"
            ) from e

        ost = ost_fallback
        used_fallback = True

    # ── Tag whether the fallback model was used ───────────────────────────────
    # results.py reads ost["_meta"]["used_fallback"] to show a quality notice.
    # Written here — after both model paths — so the flag is always present.
    ost["_meta"] = {"used_fallback": used_fallback}

    # ── Deterministic confidence override for sparse clusters ─────────────────
    # Must run after _validate_ost (fields confirmed present) and before
    # _merge_scores (scores not yet injected). Clusters with <= MIN_CLUSTER_SIZE
    # chunks get jtbd_confidence forced to "low" with the exact chunk count.
    ost = _apply_confidence_override(ost, clusters)

    # ── Inject scores — never trust the LLM to compute these ─────────────────
    # _validate_ost already confirmed no forbidden fields are present, so this
    # merge is a clean write — it does not overwrite anything the LLM produced.
    ost = _merge_scores(ost, scored_clusters)

    return ost
