"""
DATA CONTRACT (see docs/data_contracts.md):
    Input:  clusters (list[dict]), scored_clusters (list[dict]), goal (str)
    Output: OST dict {goal, opportunities: [...]} with all score fields injected

Models:
    Primary:  llama-3.3-70b-versatile
    Fallback: llama-3.1-8b-instant

Score fields injected post-parse from scored_clusters (never LLM-generated):
    importance, satisfaction, source_type_diversity,
    odi_score, evidence_robustness, priority_score
"""

import json
import os
import re
from pathlib import Path
from groq import Groq, APIStatusError

# ── Constants ─────────────────────────────────────────────────────────────────

_PRIMARY_MODEL = "llama-3.3-70b-versatile"
_FALLBACK_MODEL = "llama-3.1-8b-instant"
_MAX_TOKENS = 4096
_SYSTEM_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "system_prompt.txt"

# Score fields to inject from scored_clusters — never generated by the LLM
_INJECT_FIELDS = [
    "importance",
    "satisfaction",
    "source_type_diversity",
    "odi_score",
    "evidence_robustness",
    "priority_score",
]


# ── Internal helpers ───────────────────────────────────────────────────────────

def _load_system_prompt() -> str:
    """Load system prompt from file. Raises clearly if missing."""
    if not _SYSTEM_PROMPT_PATH.exists():
        raise FileNotFoundError(
            f"System prompt not found at {_SYSTEM_PROMPT_PATH}. "
            "Make sure prompts/system_prompt.txt is committed to the repo."
        )
    return _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()


def _build_user_message(clusters: list[dict], goal: str) -> str:
    """
    Format the user message sent to the LLM.
    Only passes cluster_id and representative_chunks — not all_chunk_ids,
    which would bloat the context window unnecessarily.
    """
    slim_clusters = [
        {
            "cluster_id": c["cluster_id"],
            "representative_chunks": [
                {"text": chunk["text"], "source_type": chunk["source_type"]}
                for chunk in c["representative_chunks"]
            ],
        }
        for c in clusters
    ]

    return (
        f"Goal: {goal}\n\n"
        f"Clusters:\n{json.dumps(slim_clusters, indent=2)}"
    )


def _call_groq(client: Groq, model: str, system: str, user: str) -> str:
    """Call Groq and return the raw text response."""
    response = client.chat.completions.create(
        model=model,
        max_tokens=_MAX_TOKENS,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    )
    return response.choices[0].message.content.strip()


def _parse_json(raw: str) -> dict:
    """
    Attempt to parse JSON from an LLM response using a cascade of repair
    strategies. Each strategy tries to recover from a different class of
    LLM formatting mistake.

    Repair cascade (stops at the first success):
        0. Fence stripping     — model wrapped JSON in ```...``` blocks
        1. Clean parse         — response was already valid JSON after fence strip
        2. raw_decode          — model added preamble text before the opening brace,
                                 or appended explanation text after the closing brace
        3. Trailing commas     — model emitted trailing commas before ] or }
        4. raw_decode + commas — model did both: preamble/suffix AND trailing commas

    Raises json.JSONDecodeError only when all four strategies fail, so that
    the caller (build_ost) can escalate to the fallback model.
    """

    # ── Repair 0: strip markdown fences ──────────────────────────────────────
    # Some models wrap their JSON in ```json ... ``` even when told not to.
    # We strip the fence lines so subsequent parse attempts work on clean text.
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        # Drop the opening fence line; also drop the closing ``` line if present.
        cleaned = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    # ── Repair 1: clean parse ─────────────────────────────────────────────────
    # Best case: the response was valid JSON after fence stripping. Try first
    # before attempting any heavier repairs.
    try:
        result = json.loads(cleaned)
        print("[llm] JSON parsed cleanly (no repairs needed)")
        return result
    except json.JSONDecodeError:
        # Not valid JSON as-is — continue to repair strategies below.
        pass

    # ── Repair 2: raw_decode from first '{' ───────────────────────────────────
    # json.JSONDecoder.raw_decode(s, idx) starts decoding at position idx and
    # stops as soon as it has read one complete JSON value, ignoring everything
    # after it. This handles two failure modes in a single step:
    #   (a) Preamble text — model says "Here is your JSON:" before the brace.
    #   (b) Trailing text — model appends "Let me know if..." after the brace.
    # By starting at the first '{' we skip the preamble; raw_decode ignores
    # anything beyond the closing '}' automatically.
    brace_pos = cleaned.find("{")
    if brace_pos != -1:
        try:
            obj, _ = json.JSONDecoder().raw_decode(cleaned, brace_pos)
            print(
                f"[llm] JSON repair succeeded via: raw_decode "
                f"(skipped {brace_pos} chars of preamble)"
            )
            return obj
        except json.JSONDecodeError:
            # The JSON block itself is malformed — try more repairs below.
            pass

    # ── Repair 3: trailing comma removal ─────────────────────────────────────
    # LLMs occasionally emit trailing commas before ] or } — valid in many
    # languages but illegal in JSON. A simple regex catches the common cases:
    #   {"key": "value",}   →  {"key": "value"}
    #   ["a", "b",]         →  ["a", "b"]
    # We apply the regex to the full cleaned string, then retry json.loads.
    comma_cleaned = re.sub(r",\s*([}\]])", r"\1", cleaned)
    try:
        result = json.loads(comma_cleaned)
        print("[llm] JSON repair succeeded via: trailing comma removal")
        return result
    except json.JSONDecodeError:
        # Still not valid — try combining both repairs.
        pass

    # ── Repair 4: raw_decode + trailing comma removal ─────────────────────────
    # Last-ditch: the model added preamble/trailing text AND trailing commas.
    # Slice from the first '{', strip trailing commas, then use raw_decode.
    # raw_decode is used again (rather than json.loads) to also tolerate any
    # remaining trailing text after the repaired closing brace.
    if brace_pos != -1:
        try:
            slice_from_brace = cleaned[brace_pos:]
            # Strip trailing commas in the sliced block first.
            slice_comma_cleaned = re.sub(r",\s*([}\]])", r"\1", slice_from_brace)
            obj, _ = json.JSONDecoder().raw_decode(slice_comma_cleaned, 0)
            print("[llm] JSON repair succeeded via: raw_decode + trailing comma removal")
            return obj
        except json.JSONDecodeError:
            pass

    # ── All repairs failed ────────────────────────────────────────────────────
    # Raise so build_ost can escalate to the fallback model. We surface the
    # original raw text in the message to make debugging easier.
    print("[llm] All JSON repair strategies failed — escalating to fallback model")
    raise json.JSONDecodeError(
        f"All repair strategies exhausted. Raw response (first 300 chars): "
        f"{raw[:300]!r}",
        raw,
        0,
    )


def _merge_scores(ost: dict, scored_clusters: list[dict]) -> dict:
    """
    Inject score fields from scored_clusters into each opportunity.
    Matches on cluster_id. Sets all score fields to null if no match found.
    Mutates ost in place and returns it.
    """
    scores_by_id: dict[int, dict] = {
        sc["cluster_id"]: sc for sc in scored_clusters
    }

    for opportunity in ost.get("opportunities", []):
        cluster_id = opportunity.get("cluster_id")
        sc = scores_by_id.get(cluster_id)

        for field in _INJECT_FIELDS:
            opportunity[field] = sc[field] if sc and field in sc else None

    return ost


# ── Public interface ───────────────────────────────────────────────────────────

def build_ost(
    clusters: list[dict],
    scored_clusters: list[dict],
    goal: str,
) -> dict:
    """
    Call Groq to generate JTBD + solutions for each cluster, then inject
    ODI scores from scored_clusters to produce the final OST dict.

    Args:
        clusters:        output of clusterer.py
        scored_clusters: output of odi_scorer.py — must be populated before calling
        goal:            product goal string from st.session_state["goal"]

    Returns:
        OST dict matching the approved schema in docs/llm_output_schema.json

    Raises:
        RuntimeError: if both primary and fallback models fail to return valid JSON
    """
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    system = _load_system_prompt()
    user = _build_user_message(clusters, goal)

    # ── Primary model attempt ─────────────────────────────────────────────────
    # We separate the API call from the JSON parse so we can distinguish two
    # very different failure modes:
    #   - APIStatusError: the request itself failed (rate limit, token limit,
    #     network issue). Repair strategies are useless here — go straight to
    #     the fallback model.
    #   - json.JSONDecodeError: we got a response but it wasn't valid JSON even
    #     after _parse_json exhausted all repair strategies. Also fall back, but
    #     for a different reason.
    try:
        raw = _call_groq(client, _PRIMARY_MODEL, system, user)
    except APIStatusError as e:
        # API-level failure (e.g. 413 token limit on free tier, 429 rate limit).
        # No point running repair logic — the model never sent a response body.
        # Log and immediately try the fallback model.
        print(f"[llm] Primary model API error ({e.status_code}), switching to fallback")
        raw = None

    if raw is not None:
        # We have a response — run the full repair cascade before giving up.
        try:
            ost = _parse_json(raw)
        except json.JSONDecodeError:
            # _parse_json already logged the failure and tried every repair.
            # Now escalate to the fallback model.
            print(f"[llm] Primary model JSON unrecoverable, switching to fallback")
            raw = None  # signal to the fallback block below

    if raw is None:
        # ── Fallback model attempt ────────────────────────────────────────────
        # We reach here either because the primary API call failed, or because
        # _parse_json could not recover the primary response.
        # The fallback model (8b) is smaller and faster but less reliable for
        # complex JSON — so we still run the full repair cascade on its response.
        try:
            raw_fallback = _call_groq(client, _FALLBACK_MODEL, system, user)
        except APIStatusError as e:
            raise RuntimeError(
                f"Fallback model API error ({e.status_code}). "
                "Check GROQ_API_KEY and request size."
            ) from e

        try:
            ost = _parse_json(raw_fallback)
        except json.JSONDecodeError as e:
            # Both models and all repair strategies failed. Surface the raw
            # response so the developer can diagnose the prompt/model issue.
            raise RuntimeError(
                f"Both {_PRIMARY_MODEL} and {_FALLBACK_MODEL} returned invalid JSON "
                f"after all repair strategies. Last error: {e}\n"
                f"Last raw response:\n{raw_fallback}"
            ) from e

    # ── Inject scores — never trust the LLM to compute these ─────────────────
    ost = _merge_scores(ost, scored_clusters)

    return ost
