"""
DATA CONTRACT (see docs/data_contracts.md):
    Input:  clusters (list[dict]), scored_clusters (list[dict]), goal (str)
    Output: OST dict {goal, opportunities: [...]} with all score fields injected

Models:
    Primary:  llama-3.1-8b-instant
    Fallback: llama-3.3-70b-versatile

Score fields injected post-parse from scored_clusters (never LLM-generated):
    importance, satisfaction, source_type_diversity,
    odi_score, evidence_robustness, priority_score
"""

import json
import os
from pathlib import Path
from groq import Groq

# ── Constants ─────────────────────────────────────────────────────────────────

_PRIMARY_MODEL = "llama-3.3-70b-versatile"
_FALLBACK_MODEL = "llama-3.1-8b-instant"
_MAX_TOKENS = 4096
_SYSTEM_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "system_prompt.txt"

# Score fields to inject from scored_clusters — never generated by the LLM
_INJECT_FIELDS = [
    "importance",
    "satisfaction",
    "source_type_diversity",
    "odi_score",
    "evidence_robustness",
    "priority_score",
]


# ── Internal helpers ───────────────────────────────────────────────────────────

def _load_system_prompt() -> str:
    """Load system prompt from file. Raises clearly if missing."""
    if not _SYSTEM_PROMPT_PATH.exists():
        raise FileNotFoundError(
            f"System prompt not found at {_SYSTEM_PROMPT_PATH}. "
            "Make sure prompts/system_prompt.txt is committed to the repo."
        )
    return _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()


def _build_user_message(clusters: list[dict], goal: str) -> str:
    """
    Format the user message sent to the LLM.
    Only passes cluster_id and representative_chunks — not all_chunk_ids,
    which would bloat the context window unnecessarily.
    """
    slim_clusters = [
        {
            "cluster_id": c["cluster_id"],
            "representative_chunks": [
                {"text": chunk["text"], "source_type": chunk["source_type"]}
                for chunk in c["representative_chunks"]
            ],
        }
        for c in clusters
    ]

    return (
        f"Goal: {goal}\n\n"
        f"Clusters:\n{json.dumps(slim_clusters, indent=2)}"
    )


def _call_groq(client: Groq, model: str, system: str, user: str) -> str:
    """Call Groq and return the raw text response."""
    response = client.chat.completions.create(
        model=model,
        max_tokens=_MAX_TOKENS,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    )
    return response.choices[0].message.content.strip()


def _parse_json(raw: str) -> dict:
    """
    Parse JSON from LLM response.
    Strips accidental markdown fences if the model ignored the instruction.
    Raises json.JSONDecodeError on failure so the caller can retry.
    """
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        # Strip ```json ... ``` fences
        lines = cleaned.splitlines()
        cleaned = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
    return json.loads(cleaned)


def _merge_scores(ost: dict, scored_clusters: list[dict]) -> dict:
    """
    Inject score fields from scored_clusters into each opportunity.
    Matches on cluster_id. Sets all score fields to null if no match found.
    Mutates ost in place and returns it.
    """
    scores_by_id: dict[int, dict] = {
        sc["cluster_id"]: sc for sc in scored_clusters
    }

    for opportunity in ost.get("opportunities", []):
        cluster_id = opportunity.get("cluster_id")
        sc = scores_by_id.get(cluster_id)

        for field in _INJECT_FIELDS:
            opportunity[field] = sc[field] if sc and field in sc else None

    return ost


# ── Public interface ───────────────────────────────────────────────────────────

def build_ost(
    clusters: list[dict],
    scored_clusters: list[dict],
    goal: str,
) -> dict:
    """
    Call Groq to generate JTBD + solutions for each cluster, then inject
    ODI scores from scored_clusters to produce the final OST dict.

    Args:
        clusters:        output of clusterer.py
        scored_clusters: output of odi_scorer.py — must be populated before calling
        goal:            product goal string from st.session_state["goal"]

    Returns:
        OST dict matching the approved schema in docs/llm_output_schema.json

    Raises:
        RuntimeError: if both primary and fallback models fail to return valid JSON
    """
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    system = _load_system_prompt()
    user = _build_user_message(clusters, goal)

    # --- Primary model attempt ---
    raw = _call_groq(client, _PRIMARY_MODEL, system, user)
    try:
        ost = _parse_json(raw)
    except json.JSONDecodeError:
        # --- Fallback model attempt ---
        raw = _call_groq(client, _FALLBACK_MODEL, system, user)
        try:
            ost = _parse_json(raw)
        except json.JSONDecodeError as e:
            raise RuntimeError(
                f"Both {_PRIMARY_MODEL} and {_FALLBACK_MODEL} returned invalid JSON. "
                f"Last error: {e}\nLast raw response:\n{raw}"
            ) from e

    # --- Inject scores — never trust the LLM to compute these ---
    ost = _merge_scores(ost, scored_clusters)

    return ost
