import json
import os
import re
from groq import Groq
from dotenv import load_dotenv
load_dotenv()

# Load prompt
system_prompt = open("prompts/system_prompt.txt").read()

# Your 3 test clusters
goal = "Increase weekly active usage of the Lidl Plus app"

clusters = [
    {
        "cluster_id": 0,
        "representative_chunks": [
            {"text": "App takes too long to load. No good in a busy store environment.", "source_type": "review"},
            {"text": "Great deals and easy to use. Would be 5 stars if the app loaded a bit faster.", "source_type": "review"},
            {"text": "Could be much better. App is slow and sometimes the coupons don't load.", "source_type": "review"}
        ],
        "all_chunk_ids": ["lidl_004", "lidl_007", "lidl_036"]
    },
    {
        "cluster_id": 1,
        "representative_chunks": [
            {"text": "This app has cost me money by not working at checkout. Furious.", "source_type": "review"},
            {"text": "Mostly very good. Had one instance where a coupon didn't work at checkout.", "source_type": "review"},
            {"text": "Good app with useful coupons. Sometimes the barcode scanner is a bit slow.", "source_type": "review"}
        ],
        "all_chunk_ids": ["lidl_026", "lidl_019", "lidl_030"]
    },
    {
        "cluster_id": 2,
        "representative_chunks": [
            {"text": "Love the savings but wish the app would remember my preferences better.", "source_type": "review"},
            {"text": "Really helpful app. Minor suggestion: add a shopping list feature.", "source_type": "review"},
            {"text": "Good app! Wish it showed more stores or had a better map feature.", "source_type": "review"}
        ],
        "all_chunk_ids": ["lidl_011", "lidl_038", "lidl_001"]
    }
]

# Build user message
user_message = f"Goal: {goal}\n\nClusters:\n{json.dumps(clusters, indent=2)}"

# Call Groq
client = Groq(api_key=os.environ["GROQ_API_KEY"])

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message}
    ]
)

raw = response.choices[0].message.content
raw = re.sub(r',\s*}', '}', raw)
raw = re.sub(r',\s*]', ']', raw)
raw = raw.strip().strip('`')
print("=== RAW OUTPUT ===")
print(raw)
print()

# Validate
print("=== VALIDATION ===")
try:
    parsed = json.loads(raw)
    print("✅ Valid JSON")
except json.JSONDecodeError as e:
    print(f"❌ Invalid JSON: {e}")
    exit()

opps = parsed.get("opportunities", [])

# Check 1: correct number of opportunities
if len(opps) == len(clusters):
    print(f"✅ Correct opportunity count: {len(opps)}")
else:
    print(f"❌ Wrong opportunity count: got {len(opps)}, expected {len(clusters)}")

# Check 2: JTBD format
for o in opps:
    jtbd = o.get("jtbd", "")
    if jtbd.startswith("When I") and "I want" in jtbd and "so I can" in jtbd:
        print(f"✅ JTBD format OK: {jtbd[:80]}...")
    else:
        print(f"❌ JTBD format FAIL: {jtbd[:80]}")

# Check 3: no ODI fields generated by LLM
for o in opps:
    for field in ["priority_score", "importance", "satisfaction", "opportunity_score"]:
        if field in o:
            print(f"❌ LLM generated forbidden field: {field}")
        else:
            print(f"✅ Field '{field}' correctly absent")

# Check 4: risk values
for o in opps:
    for s in o.get("solutions", []):
        for a in s.get("assumptions", []):
            risk = a.get("risk", "")
            if risk in ["low", "medium", "high"]:
                print(f"✅ Risk value OK: {risk}")
            else:
                print(f"❌ Invalid risk value: '{risk}'")

# Check 5: solution count per opportunity
for o in opps:
    n = len(o.get("solutions", []))
    if 2 <= n <= 3:
        print(f"✅ Solution count OK for cluster {o['cluster_id']}: {n}")
    else:
        print(f"❌ Solution count FAIL for cluster {o['cluster_id']}: {n}")